### ISSUE TITLE
tset on vot2018

### ISSUE THREAD

**Issue by aaahuia** [huanglianghua/siamfc-pytorch#46]
When  i  test on vot2018

    root_dir = os.path.join('G:/practice/data'+'/VOT2018')
    e = ExperimentVOT(root_dir,version=2018,experiments='unsupervised')
    
    e.run(tracker)

    e.report([tracker.name])

I got 

  Found results, skipping tiger
--Sequence 57/59: traffic
  Found results, skipping traffic
--Sequence 58/59: wiper
  Found results, skipping wiper
--Sequence 59/59: zebrafish1
  Found results, skipping zebrafish1
Evaluating triplet
Traceback (most recent call last):

  File "G:\practice\TripleFC\tools\test.py", line 37, in <module>
    e.report([tracker.name])

  File "E:\anaconda\1\envs\siamfc\lib\site-packages\got10k\experiments\vot.py", line 361, in report
    ious[seq_name][:len(seq_ious), :] = seq_ious

ValueError: could not broadcast input array from shape (0) into shape (0,325)

How to solve this problem？I don't know where I went wrong.

**Comment by wangchenw** [comment]
能留个联系方式吗？一起学习下
