### ISSUE TITLE
test vot2018 AttributeError: shape

### ISSUE THREAD

**Issue by dev-lyj** [huanglianghua/siamfc-pytorch#56]
Files already downloaded.
Running tracker SiamFC on VOT...
Running supervised experiment...
--Sequence 1/60: ants1
 Repetition: 1
Traceback (most recent call last):
  File "E:/Postgraduate/project/target tracking/siamfc-pytorch-master/siamfc-pytorch-master/tools/test.py", line 27, in <module>
    e.run(tracker)
  File "E:\Postgraduate\soft\result\Anaconda\lib\site-packages\got10k\experiments\vot.py", line 71, in run
    self.run_supervised(tracker, visualize)
  File "E:\Postgraduate\soft\result\Anaconda\lib\site-packages\got10k\experiments\vot.py", line 126, in run_supervised
    tracker.init(frame, anno_rects[0])
  File "E:\Postgraduate\soft\result\Anaconda\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "E:\Postgraduate\project\target tracking\siamfc-pytorch-master\siamfc-pytorch-master\siamfc\siamfc.py", line 159, in init
    z = ops.crop_and_resize(
  File "E:\Postgraduate\project\target tracking\siamfc-pytorch-master\siamfc-pytorch-master\siamfc\ops.py", line 106, in crop_and_resize
    pads = np.concatenate((-corners[:2], corners[2:] - img.shape[:2]))
  File "E:\Postgraduate\soft\result\Anaconda\lib\site-packages\PIL\Image.py", line 546, in __getattr__
    raise AttributeError(name)
AttributeError: shape

**Comment by dev-lyj** [comment]
.
